gadepall/ncert-signal

app/mgf.tex
=> z transform of ap

app/mgf.tex
=> Sum of AP via Z-Transform Appendix

ncert-maths/sequences.tex
Reverts gadepall/ncert-signal#34
=> Revert "NCERT MATHS 11/9/3/2"

ncert-maths/sequences.tex
=> physics 10.5.2.13 -book 3.0.19

ncert-maths/z-transform.tex
=> maths 11.9.3.24 -book 3.0.18

main.tex, ncert-physics/systems.tex
=> Add ncert-physics question 11.14.17 as 7.0.1

ncert-maths/z-transform.tex
Name - Tejas Mehtre
Roll no. - ee23btech11059
=> Added question of Discrete Assignment 2 (11.5.3.8 as 4.0.23)

ncert-physics/systems.tex
=> analog 11.14.8 - book 7.0.2 wrt repo EE23BTECH11202

ncert-physics/analog.tex
Reverts gadepall/ncert-signal#305
=> Revert "Update analog.tex"

ncert-maths/z-transform.tex
Name-Tejas Mehtre
Roll no- ee23btech11059
=> Added Question of discrete assignment (11.9.4.6 as 3.0.32 wrt repo)

ncert-physics/analog.tex
Name- Tejas Mehtre
Roll no. - ee23btech11059
=> Added question of Analog Assignment (11.15.7 as 1.0.21)

ncert-maths/contour_integration.tex, ncert-maths/sequences.tex, ncert-physics/analog.tex
Reverts gadepall/ncert-signal#414
=> Revert "Analog(11.15.15 as 1.0.33) and Discrete(10.5.3.15 as 5.19 , 11.9.5.3 as 4.0.35) by ee23btech11062(questions)"

ncert-maths/contour_integration.tex, ncert-physics/analog.tex
Reverts gadepall/ncert-signal#447
=> Revert "(Analog) 11.15 Q16 as 1.0.22,(Discrete) 11.9.5 Q4 as 5.21, (Discrete) 10.5.4 Q16 as 5.22 by ee23btech11038"

ncert-maths/contour_integration.tex, ncert-maths/sequences.tex, ncert-physics/analog.tex
Reverts gadepall/ncert-signal#457
=> Revert "Analog(11.15.15 as 1.0.35) and Discrete(10.5.3.15 as 5.20 , 11.9.5.3 as 4.0.36) by ee23btech11062(questions)"

ncert-maths/contour_integration.tex, ncert-physics/analog.tex
Reverts gadepall/ncert-signal#458
=> Revert "analog(11.15.18 as 1.0.21) and discrete(11.9.5.6 as 5.16,10.5.3.18 as 5.17) by ee23btech11028(question)"

ncert-maths/sequences.tex
=> Discrete(10.5.2-9 as 4.0.37 , 11.9.3-19 as 4.0.38) by ee23btech11222(questions)

ncert-physics/analog.tex
ee23btech11041
MD AYAAN ASHRAF
=> 11.14.7 as 1.0.49 (question) by ee23btech11041

ncert-maths/contour_integration.tex, ncert-maths/z-transform.tex, ncert-physics/analog.tex
=> NCERT Discrete-10.5.3-7 as 5.28, NCERT Discrete-11.9.4-5 as 3.52, NCERT-Analog-11.15-6 as 1.52

ncert-maths/z-transform.tex
Name-Tejas 
Roll no- ee23btech11059
=> Adding the solution to 11/9/4/6 Discrete Assignment

ncert-maths/z-transform.tex
Name-Tejas Mehtre
Roll no. - ee23btech11059
=> Discrete assignment fixing print issue in Z transform section for the solution. 11/9/4/6 as 3.0.30 wrt repo

ncert-maths/sequences.tex
=> discrete 11.9.1.1 as 4.0.45 wrt book repo  (EE23BTECH11024)

ncert-maths/sequences.tex
Reverts gadepall/ncert-signal#592
=> Revert "discrete 11.9.1.1 as 4.0.45 wrt book repo (EE23BTECH11024)"

ncert-physics/analog.tex
Kunal Thorawade
ee23btech11035
=> Ncert-physics_11.14.18 - book_1.0.59

app/mgf.tex, ncert-maths/z-transform.tex
Reverts gadepall/ncert-signal#661
=> Revert "discrete 11.9.5.14 as 3.0.45 wrt book repo (EE23BTECH11024) (Karthik Yadav)"

app/mgf.tex, ncert-maths/z-transform.tex
Reverts gadepall/ncert-signal#736
=> Revert "discrete 11.9.5.14 as 3.0.45 wrt book (EE23BTECH11024) (KARTHIK YADAV)"
